version: '3'
services:
  db:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
  web:
    build: .
    environment:
      RAILS_ENV: development
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/src
      - bundle-data:/usr/local/bundle
    ports:
      - "7000:3000"
    depends_on:
      - db
volumes:
  bundle-data: